import component from "../form.vue";

const name = component.name; // 组件标签名

const title = "应聘填表组件"; // 组件title

const description = `应聘填表组件`; // 组件描述信息

const dev = {
    form: {
        ui_form_01: {
            upload: {
                url: "dynamicFile/upload.do"
            },
            submit: {
                url: "../data/form.json",
                params: {
                    doclibCode: "BASIC_INFO",
                    metaMap: {}
                }
            },
            formTitle: {
                isShow: true,
                name: "填写信息"
            },
            labelWidth: "120px",
            sysAdapter: "sykAdapter",
            typeAdapter: "talentAdapter",
            toUrl: "../pages/index.html",
            formItem: [{
                type: "fileimg",
                label: "照片：",
                btnName: "上传附件",
                model: "coverId",
                field: "coverId"
            }, {
                type: "text",
                label: "姓名：",
                model: "sysTopic",
                field: "sysTopic"
            }, {
                type: "text",
                label: "考生身份：",
                model: "type",
                field: "type"
            }, {
                type: "radio",
                label: "性别：",
                radio: [{
                    label: "男",
                    value: "男"
                }, {
                    label: "女",
                    value: "女"
                }],
                model: "sex",
                field: "sex"
            }, {
                type: "text",
                label: "生源地：",
                model: "address",
                field: "address"
            }, {
                type: "date",
                label: "出生日期：",
                format: "yyyy - MM - dd",
                valueFormat: "timestamp",
                model: "date1",
                field: "birth"
            }, {
                type: "text",
                label: "考试地点：",
                model: "place",
                field: "place"
            }, {
                type: "text",
                label: "身份证号：",
                model: "cardId",
                field: "cardId"
            }, {
                type: "text",
                label: "报考专业：",
                model: "specialty",
                field: "specialty"
            }, {
                type: "text",
                label: "政治面貌：",
                model: "politicalStatus",
                field: "politicalStatus"
            }, {
                type: "text",
                label: "专业类别：",
                model: "cat1",
                field: "cat1"
            }, {
                type: "text",
                label: "民族：",
                model: "race",
                field: "race"
            }, {
                type: "text",
                label: "报考单位：",
                model: "workAddress",
                field: "workAddress"
            }, {
                type: "text",
                label: "毕业院校：",
                model: "graduateInstitutions",
                field: "graduateInstitutions"
            }, {
                type: "text",
                label: "学历：",
                model: "education",
                field: "education"
            }, {
                type: "text",
                label: "学位：",
                model: "degree",
                field: "degree"
            }, {
                type: "text",
                label: "所学专业：",
                model: "specialty1",
                field: "specialty1"
            }, {
                type: "text",
                label: "外语水平：",
                model: "wysp",
                field: "wysp"
            }, {
                type: "text",
                label: "计算机水平：",
                model: "jsjsp",
                field: "jsjsp"
            }, {
                type: "text",
                label: "现工作单位：",
                model: "org",
                field: "org"
            }, {
                type: "text",
                label: "工作性质：",
                model: "firstOrg",
                field: "firstOrg"
            }, {
                type: "textarea",
                label: "资格证书：",
                rows: 5,
                model: "qualification",
                field: "qualification"
            }, {
                type: "textarea",
                label: "社团活动：",
                rows: 5,
                model: "activities",
                field: "activities"
            }, {
                type: "textarea",
                label: "专长：",
                rows: 5,
                model: "specialties",
                field: "specialties"
            }, {
                type: "text",
                label: "婚姻状况：",
                model: "maritalStatus",
                field: "maritalStatus"
            }, {
                type: "text",
                label: "健康状况：",
                model: "health",
                field: "health"
            }, {
                type: "text",
                label: "身高：",
                model: "height",
                field: "height"
            }, {
                type: "text",
                label: "联系电话：",
                model: "phone",
                field: "phone"
            }, {
                type: "text",
                label: "邮编：",
                model: "mailCode",
                field: "mailCode"
            }, {
                type: "text",
                label: "电子邮箱：",
                model: "email",
                field: "email"
            }, {
                type: "textarea",
                label: "通讯地址：",
                rows: 3,
                model: "mailAddress",
                field: "mailAddress"
            }, {
                type: "textarea",
                label: "教育经历：",
                rows: 5,
                model: "experience",
                field: "experience"
            }, {
                type: "textarea",
                label: "学术成果：",
                rows: 5,
                model: "achievements",
                field: "achievements"
            }, {
                type: "textarea",
                label: "奖惩成果：",
                rows: 5,
                model: "awardRecords",
                field: "awardRecords"
            }, {
                type: "textarea",
                label: "实习经历：",
                rows: 5,
                model: "internshipExperience",
                field: "internshipExperience"
            }, {
                type: "textarea",
                label: "工作经历：",
                rows: 5,
                model: "wordExperience",
                field: "wordExperience"
            }, {
                type: "textarea",
                label: "家庭情况：",
                rows: 5,
                model: "familySituation",
                field: "familySituation"
            }, {
                type: "textarea",
                label: "其他情况：",
                rows: 5,
                model: "otherSituation",
                field: "otherSituation"
            }, {
                type: "textarea",
                label: "补充资料说明：",
                rows: 5,
                model: "description",
                field: "description"
            }, {
                type: "button",
                name: "提交"
            }]
        }
    }
};

const prod = {
    form: {
        ui_form_01: {
            upload: {
                url: "dynamicFile/upload.do"
            },
            submit: {
                url: "spc/prodb/saveItem.do",
                params: {
                    doclibCode: "BASIC_INFO",
                    metaMap: {}
                }
            },
            formTitle: {
                isShow: true,
                name: "填写信息"
            },
            labelWidth: "120px",
            sysAdapter: "sykAdapter",
            typeAdapter: "talentAdapter",
            toUrl: "../pages/index.html",
            formItem: [{
                type: "fileimg",
                label: "照片：",
                btnName: "上传附件",
                model: "coverId",
                field: "coverId"
            }, {
                type: "text",
                label: "姓名：",
                model: "sysTopic",
                field: "sysTopic"
            }, {
                type: "text",
                label: "考生身份：",
                model: "type",
                field: "type"
            }, {
                type: "radio",
                label: "性别：",
                radio: [{
                    label: "男",
                    value: "男"
                }, {
                    label: "女",
                    value: "女"
                }],
                model: "sex",
                field: "sex"
            }, {
                type: "text",
                label: "生源地：",
                model: "address",
                field: "address"
            }, {
                type: "date",
                label: "出生日期：",
                format: "yyyy - MM - dd",
                valueFormat: "timestamp",
                model: "date1",
                field: "birth"
            }, {
                type: "text",
                label: "考试地点：",
                model: "place",
                field: "place"
            }, {
                type: "text",
                label: "身份证号：",
                model: "cardId",
                field: "cardId"
            }, {
                type: "text",
                label: "报考专业：",
                model: "specialty",
                field: "specialty"
            }, {
                type: "text",
                label: "政治面貌：",
                model: "politicalStatus",
                field: "politicalStatus"
            }, {
                type: "text",
                label: "专业类别：",
                model: "cat1",
                field: "cat1"
            }, {
                type: "text",
                label: "民族：",
                model: "race",
                field: "race"
            }, {
                type: "text",
                label: "报考单位：",
                model: "workAddress",
                field: "workAddress"
            }, {
                type: "text",
                label: "毕业院校：",
                model: "graduateInstitutions",
                field: "graduateInstitutions"
            }, {
                type: "text",
                label: "学历：",
                model: "education",
                field: "education"
            }, {
                type: "text",
                label: "学位：",
                model: "degree",
                field: "degree"
            }, {
                type: "text",
                label: "所学专业：",
                model: "specialty1",
                field: "specialty1"
            }, {
                type: "text",
                label: "外语水平：",
                model: "wysp",
                field: "wysp"
            }, {
                type: "text",
                label: "计算机水平：",
                model: "jsjsp",
                field: "jsjsp"
            }, {
                type: "text",
                label: "现工作单位：",
                model: "org",
                field: "org"
            }, {
                type: "text",
                label: "工作性质：",
                model: "firstOrg",
                field: "firstOrg"
            }, {
                type: "textarea",
                label: "资格证书：",
                rows: 5,
                model: "qualification",
                field: "qualification"
            }, {
                type: "textarea",
                label: "社团活动：",
                rows: 5,
                model: "activities",
                field: "activities"
            }, {
                type: "textarea",
                label: "专长：",
                rows: 5,
                model: "specialties",
                field: "specialties"
            }, {
                type: "text",
                label: "婚姻状况：",
                model: "maritalStatus",
                field: "maritalStatus"
            }, {
                type: "text",
                label: "健康状况：",
                model: "health",
                field: "health"
            }, {
                type: "text",
                label: "身高：",
                model: "height",
                field: "height"
            }, {
                type: "text",
                label: "联系电话：",
                model: "phone",
                field: "phone"
            }, {
                type: "text",
                label: "邮编：",
                model: "mailCode",
                field: "mailCode"
            }, {
                type: "text",
                label: "电子邮箱：",
                model: "email",
                field: "email"
            }, {
                type: "textarea",
                label: "通讯地址：",
                rows: 3,
                model: "mailAddress",
                field: "mailAddress"
            }, {
                type: "textarea",
                label: "教育经历：",
                rows: 5,
                model: "experience",
                field: "experience"
            }, {
                type: "textarea",
                label: "学术成果：",
                rows: 5,
                model: "achievements",
                field: "achievements"
            }, {
                type: "textarea",
                label: "奖惩成果：",
                rows: 5,
                model: "awardRecords",
                field: "awardRecords"
            }, {
                type: "textarea",
                label: "实习经历：",
                rows: 5,
                model: "internshipExperience",
                field: "internshipExperience"
            }, {
                type: "textarea",
                label: "工作经历：",
                rows: 5,
                model: "wordExperience",
                field: "wordExperience"
            }, {
                type: "textarea",
                label: "家庭情况：",
                rows: 5,
                model: "familySituation",
                field: "familySituation"
            }, {
                type: "textarea",
                label: "其他情况：",
                rows: 5,
                model: "otherSituation",
                field: "otherSituation"
            }, {
                type: "textarea",
                label: "补充资料说明：",
                rows: 5,
                model: "description",
                field: "description"
            }, {
                type: "button",
                name: "提交"
            }]
        }
    }
};

const platform = 'PC';
const pageType = ['others'];
const resourceType = ['others'];

export { name, title, dev, prod, description, platform, pageType, resourceType };